### PR TITLE
Fix cache path for -force_load issue

### PR DESCRIPTION
**Pull request by blastmann**
### Description

Replace `PODS_ROOT` with `SRCROOT` to avoid relative path linking issue.

### References

Fix issue #125 

### Checklist
- [x] I've added at least one test that validates that my change is working, if appropriate
- [x] I've followed the code style of the rest of the project
- [x] I've read the [Contribution Guidelines](CONTRIBUTING.md)
- [x] I've updated the documentation if necessary

❤️ Thanks for contributing to the 🏈 Rugby!

### CODE REVIEW

**Comment by swiftyfinch** [comment]
Hey, I will check it too.
There are some issues with your pull request.

**Comment by swiftyfinch** [comment]
Sorry, I can't approve this request.
The fix doesn't work, some of the tests are failed.
You can find more information here https://github.com/swiftyfinch/Rugby/issues/125#issuecomment-1025118772

**Comment by swiftyfinch** [comment]
But anyway, feel free to open a new one or reopen this one if you have another solution.

**Comment by blastmann** [comment]
> But anyway, feel free to open a new one or reopen this one if you have another solution.

Hahaha, I'm in a vacation and forget this PR. I fix it with a new solution.

**Pull request closed without merging**
