### PR TITLE
New variable in xcconfig to fix `-force_load` issue

### PR DESCRIPTION
**Pull request by blastmann**
### Description

Define a new xcconfig variable to avoid duplicate symbols.

### References

Fix issue #125 

### Checklist
- [x] I've added at least one test that validates that my change is working, if appropriate
- [x] I've followed the code style of the rest of the project
- [x] I've read the [Contribution Guidelines](CONTRIBUTING.md)
- [x] I've updated the documentation if necessary

❤️ Thanks for contributing to the 🏈 Rugby!

### CODE REVIEW

**Comment by swiftyfinch** [comment]
Hello!

I tried to add this to TestProject `Podfile` and test your solution:
```diff
-  use_frameworks!
+ pod 'hippy', '2.11.6'
```

And I got an error `1265 duplicate symbols for architecture x86_64`.
It looks like the issue still exists:
```
duplicate symbol '_OBJC_CLASS_$_PodsDummy_hippy' in:
    ~/Desktop/Rugby/TestProject/TestProject/../Pods/../.rugby/build/Debug-iphonesimulator/hippy/libhippy.a(hippy-dummy.o)
    ~/Desktop/Rugby/TestProject/.rugby/build/Debug-iphonesimulator/hippy/libhippy.a(hippy-dummy.o)
```
Probably, we can't fix it with any variable.

**Comment by blastmann** [comment]
Oh no.

Let me try with you `TestProject`, I'll close this PR first.

**Comment by blastmann** [comment]
> Hello!
> 
> I tried to add this to TestProject `Podfile` and test your solution:
> 
> ```diff
> -  use_frameworks!
> + pod 'hippy', '2.11.6'
> ```
> 
> And I got an error `1265 duplicate symbols for architecture x86_64`. It looks like the issue still exists:
> 
> ```
> duplicate symbol '_OBJC_CLASS_$_PodsDummy_hippy' in:
>     ~/Desktop/Rugby/TestProject/TestProject/../Pods/../.rugby/build/Debug-iphonesimulator/hippy/libhippy.a(hippy-dummy.o)
>     ~/Desktop/Rugby/TestProject/.rugby/build/Debug-iphonesimulator/hippy/libhippy.a(hippy-dummy.o)
> ```
> 
> Probably, we can't fix it with any variable.

You are definitely correct. 

Maybe the only way to use variable is set the rugby cache as a sub directory in `${BUILD_DIR}`.

**Comment by swiftyfinch** [comment]
I don't like `${BUILD_DIR}`, because the user can clear up `DerivedData` at any time.
And it can lead to unexpected issues in Rugby.

I like to keep `.rugby` folder outside `DerivedData`. It is just a more reliable way.

**Pull request closed without merging**
