### PR TITLE
Add ignoreGitDirtyLocalPods

### PR DESCRIPTION
**Pull request by mlch911**
### Description
Add ignoreGitDirtyLocalPods flag for ignore dev pod which git is dirty.

### References
Provide links to an existing issue or external references/discussions, if appropriate.

### Checklist
- [x] I've added at least one test that validates that my change is working, if appropriate
- [x] I've followed the code style of the rest of the project
- [x] I've read the [Contribution Guidelines](CONTRIBUTING.md)
- [x] I've updated the documentation if necessary

❤️ Thanks for contributing to the 🏈 Rugby!

### CODE REVIEW

**Comment by swiftyfinch** [comment]
Hello @mlch911! Could you please describe a case when we need such a new flag?

**Comment by mlch911** [comment]
Our App has so many develop Pods to split different module. So our pod changes frequently. 
And we usually works on several Pods at once. So we need this flag to cache all other Pods we don't need for now.

**Comment by swiftyfinch** [comment]
So, do you make some changes in several pods just before using 🏈 Rugby? Is it convenient?

Have you tried such command yet?
https://github.com/swiftyfinch/Rugby/blob/main/Docs/Cache.md#build-local-pods

> If you want to focus on some local pods and cache all others:
> ```
> rugby --focus MyFocusedPod1 MyFocusedPod2
> ```
I work in huge project and pass to focus only about 10 local pods. It's pretty easy.

**Comment by mlch911** [comment]
Thanks. I may try a better solution.

**Pull request closed without merging**
