### PR TITLE
🏛️ Support Libraries

### PR DESCRIPTION
**Pull request by swiftyfinch**
### Description

I've added libraries support.
After this request we can use `Podfile` without `use_frameworks!`:
```ruby
# use_frameworks!
```

###### Todo:
- [x] Add tests for `SupportFilesPatcher`
- [x] More smoke tests?
- [x] Regress

### References

#242 #231

### Checklist (I have ...)
- [x] 🧐 Followed the code style of the rest of the project
- [ ] 📖 Updated the documentation if necessary
- [x] 👨🏻‍🔧 Added at least one test that validates that my change is working, if appropriate
- [x] 👮🏻‍♂️ Run `make lint` and fixed all warnings
- [x] ✅ Run `make test` and fixed all tests

❤️ Thanks for contributing to the 🏈 Rugby!

### CODE REVIEW

**Comment by rock88** [comment]
Hi @swiftyfinch, you 🚀 It seems I'm late 😁
I added static lib support in this commit - https://github.com/rock88/Rugby/commit/4784b8860710722908504b558b8e1aa2958c35bd

Also I faced with custom module names in my project ([PulseCore](https://github.com/kean/Pulse/blob/main/PulseCore.podspec#L4C24-L4C24), for example) and fixed that issue.
Not sure what I made all changes in right way, but in my project with lots of remote/local pods and resource bundles all works fine.

```
Pod installation complete! There are 122 dependencies from the Podfile and 174 total pods installed.

rugby -e Braintree
⚑ Cache -e Braintree
  ⚑ Build
    ✓ CLT: Xcode 15.0
    ✓ [0.3s] Reading Project
    ✓ Finding Build Targets
    ✓ [0.1s] Backuping
    ⚑ Checking Binaries Storage
      ✓ [0.4s] Calculating Storage Info
      ✓ Used: 1,57 GB (3%)
    ✓ [0.4s] Checking Binaries Storage
    ✓ [1.5s] Hashing Targets
    ✓ Finding Binaries
    ✓ Found 100% Binaries (200)
  ✓ [2.5s] Build
  ⚑ Use
    ✓ Finding Build Targets
    ✓ Hashing Targets
    ✓ [0.2s] Backuping
    ✓ Patching Product Files
    ✓ Deleting Targets (200)
    ✓ [0.1s] Saving Project
  ✓ [0.5s] Use
✓ [3.1s] Cache
✓ ⚑ Let's Roll-oll 🏈
```

I excluded only one pod - [Braintree](https://github.com/braintree/braintree_ios), because it uses `install_framework` script which not execute if use binary cache.

**Comment by swiftyfinch** [comment]
> Hi @swiftyfinch, you are 🚀 It seems I'm late 😁 I added static lib support in this commit - [rock88@4784b88](https://github.com/rock88/Rugby/commit/4784b8860710722908504b558b8e1aa2958c35bd)
> 
> Also I faced with custom module names in my project ([PulseCore](https://github.com/kean/Pulse/blob/main/PulseCore.podspec#L4C24-L4C24), for example) and fixed that issue. Not sure what I made all changes in right way, but in my project with lots of remote/local pods and resource bundles all works fine.
> 
> ```
> Pod installation complete! There are 122 dependencies from the Podfile and 174 total pods installed.
> 
> rugby -e Braintree
> ⚑ Cache -e Braintree
>   ⚑ Build
>     ✓ CLT: Xcode 15.0
>     ✓ [0.3s] Reading Project
>     ✓ Finding Build Targets
>     ✓ [0.1s] Backuping
>     ⚑ Checking Binaries Storage
>       ✓ [0.4s] Calculating Storage Info
>       ✓ Used: 1,57 GB (3%)
>     ✓ [0.4s] Checking Binaries Storage
>     ✓ [1.5s] Hashing Targets
>     ✓ Finding Binaries
>     ✓ Found 100% Binaries (200)
>   ✓ [2.5s] Build
>   ⚑ Use
>     ✓ Finding Build Targets
>     ✓ Hashing Targets
>     ✓ [0.2s] Backuping
>     ✓ Patching Product Files
>     ✓ Deleting Targets (200)
>     ✓ [0.1s] Saving Project
>   ✓ [0.5s] Use
> ✓ [3.1s] Cache
> ✓ ⚑ Let's Roll-oll 🏈
> ```
> 
> I excluded only one pod - [Braintree](https://github.com/braintree/braintree_ios), because it uses `install_framework` script which not execute if use binary cache.

Wow 🤯 
I thought you decided to get some rest at the end of the week 😅

I've reviewed your changes, and it's pretty similar to mine!
I think that it does the same work.
Did you try to use my version for your project? I've checked on mine ✅.

I need to add some unit tests, and I'm going to merge this one.

**Comment by rock88** [comment]
@swiftyfinch I checked your version and seems like it not work for test targets with own `resource_bundle`. I don't know why, but my version works for this case...

I got an error:

```
⛔️ Error: Target 'LocalPod-LocalPodTests' has not product.
```

For reproduce you can use this podspec file:

```ruby
Pod::Spec.new do |s|
  s.name     = 'LocalPod'
  s.version  = '1.0.0'
  s.summary  = 'LocalPod'
  s.homepage = "none"
  s.author   = "Khorkov Vyacheslav"
  s.source   = { :path => "*" }

  s.ios.deployment_target = '16.0'
  s.static_framework = true
  s.prefix_header_file = false
  s.source_files = "#{s.name}/Sources/**/*.swift"
  s.resource_bundles = {
    "#{s.name}Resources" => [
      "#{s.name}/{Sources,Resources}/**/*.{strings}"
    ]
  }
  s.dependency 'Moya/Core'

  s.test_spec 'Tests' do |ts|
    ts.source_files = "#{s.name}/Tests/**/*.swift"    
    ts.resource_bundle = {
      s.name + 'Tests' => "#{s.name}/Tests/**/*.{json,xcassets}"
    }
  end
end
```

And I suggest to add a simple test for check resource access:

```swift
import XCTest

final class DummyTest: XCTestCase {
    func test() throws {
        let path = Bundle.resourcesBundle.path(forResource: "dummy", ofType: "json") ?? ""
        let data = try Data(contentsOf: URL(filePath: path))
        let dummy = try JSONDecoder().decode(Dummy.self, from: data)
        XCTAssertEqual(dummy.id, "some")
    }
}

struct Dummy: Codable {
    let id: String
}

extension Bundle {
    static let resourcesBundle = Bundle.main.path(forResource: "LocalPodTests", ofType: "bundle").flatMap { Bundle(path: $0) } ??
        Bundle(for: BundleToken.self).path(forResource: "LocalPodTests", ofType: "bundle").flatMap(Bundle.init) ??
        Bundle(for: BundleToken.self)
}

private final class BundleToken {}
```

This should work for both the static libraries and frameworks.

I also found another bug in my version - I did not fix the modulemap paths in `LocalPod.unit-tests.*.xcconfig` files 🤯

**Comment by swiftyfinch** [comment]
> @swiftyfinch I checked your version and seems like it not work for test targets with own `resource_bundle`. I don't know why, but my version works for this case...
> 
> I got an error:
> 
> ```
> ⛔️ Error: Target 'LocalPod-LocalPodTests' has not product.
> ```
> 
> For reproduce you can use this podspec file:
> 
> ```ruby
> Pod::Spec.new do |s|
>   s.name     = 'LocalPod'
>   s.version  = '1.0.0'
>   s.summary  = 'LocalPod'
>   s.homepage = "none"
>   s.author   = "Khorkov Vyacheslav"
>   s.source   = { :path => "*" }
> 
>   s.ios.deployment_target = '16.0'
>   s.static_framework = true
>   s.prefix_header_file = false
>   s.source_files = "#{s.name}/Sources/**/*.swift"
>   s.resource_bundles = {
>     "#{s.name}Resources" => [
>       "#{s.name}/{Sources,Resources}/**/*.{strings}"
>     ]
>   }
>   s.dependency 'Moya/Core'
> 
>   s.test_spec 'Tests' do |ts|
>     ts.source_files = "#{s.name}/Tests/**/*.swift"    
>     ts.resource_bundle = {
>       s.name + 'Tests' => "#{s.name}/Tests/**/*.{json,xcassets}"
>     }
>   end
> end
> ```
> 
> And I suggest to add a simple test for check resource access:
> 
> ```swift
> import XCTest
> 
> final class DummyTest: XCTestCase {
>     func test() throws {
>         let path = Bundle.resourcesBundle.path(forResource: "dummy", ofType: "json") ?? ""
>         let data = try Data(contentsOf: URL(filePath: path))
>         let dummy = try JSONDecoder().decode(Dummy.self, from: data)
>         XCTAssertEqual(dummy.id, "some")
>     }
> }
> 
> struct Dummy: Codable {
>     let id: String
> }
> 
> extension Bundle {
>     static let resourcesBundle = Bundle.main.path(forResource: "LocalPodTests", ofType: "bundle").flatMap { Bundle(path: $0) } ??
>         Bundle(for: BundleToken.self).path(forResource: "LocalPodTests", ofType: "bundle").flatMap(Bundle.init) ??
>         Bundle(for: BundleToken.self)
> }
> 
> private final class BundleToken {}
> ```
> 
> This should work for both the static libraries and frameworks.
> 
> I also found another bug in my version - I did not fix the modulemap paths in `LocalPod.unit-tests.*.xcconfig` files 🤯

Thanks a lot for your thoughts!
I will try to reproduce this issue tomorrow.

@rock88 Could you open a pull request with the suggested test? It will be great 💪

**Comment by swiftyfinch** [comment]
Maybe we can improve smoke tests without iteration all over ENV combinations.
`// TODO: Need to think about this comment:`
https://github.com/swiftyfinch/Rugby/pull/245#issuecomment-1752019040

**Pull request merged**
