### PR TITLE
Add ARCH.generic

### PR DESCRIPTION
**Pull request by mlch911**
### Description
In some case, build sim with arch wouldn't work properly. Add `generic` ARCH to build without arch.

### References
In my project, build [sim x86] may not build success sometime. It says need arm64 but found x86_64. It's better build without ARCH to support old project running on simulotor.

### Checklist
- [x] I've added at least one test that validates that my change is working, if appropriate
- [x] I've followed the code style of the rest of the project
- [x] I've read the [Contribution Guidelines](CONTRIBUTING.md)
- [x] I've updated the documentation if necessary

❤️ Thanks for contributing to the 🏈 Rugby!

### CODE REVIEW

**Comment by mlch911** [comment]
the spelling check is so strict...

**Comment by swiftyfinch** [comment]
@mlch911  Hello! Sorry, can't have enough time right now. Could you add some links to documentation about `ARCH=generic`? I didn't know about this. It looks dangerous for me, because we can't know the destination arch. It like a random arch)

**Comment by swiftyfinch** [comment]
> the spelling check is so strict...

Yeah, I didn't find a better one. Could you suggest some?
BTW, you can add words to allow list or just skip this step. I can add them later.

**Comment by mlch911** [comment]
> @mlch911 Hello! Sorry, can't have enough time right now. Could you add some links to documentation about `ARCH=generic`? I didn't know about this. It looks dangerous for me, because we can't know the destination arch. It like a random arch)

It's just remove the `ARCHS` option from `xcodebuild` command.

**Comment by swiftyfinch** [comment]
@mlch911 Unfortunately, the second version of Rugby requires this `$ARCH` variable during reusing binaries process.

I noticed that it depends on architecture of `rugby` binary. If Rugby compiled for `x86_64` on mac with M1 it will select `x86_64` with the `auto` option of `arch`.

Also, there was a good https://github.com/swiftyfinch/Rugby/discussions/222#discussioncomment-5291585 from @VaslD about `EXCLUDED_ARCHS`.

In total, I think that it will be much better to improve the `auto` option without adding another workaround like `generic`. It certainly will be broken in the Rugby2.x.

**Comment by swiftyfinch** [comment]
Hello @mlch911, I'm going to use `$ arch` shell command for getting the current architecture of mac in the Rugby2.x release. Have you already tried this solution? May it will fix your problem.

**Comment by mlch911** [comment]
> Hello @mlch911, I'm going to use `$ arch` shell command for getting the current architecture of mac in the Rugby2.x release. Have you already tried this solution? May it will fix your problem.
> 
> Update: Oh, BTW I've forgotten to mention that I frozen the Rugby 1.x version. FYI: https://github.com/swiftyfinch/Rugby/releases/tag/1.23.0

This wouldn't help. My project need both arm and x86 arch to run on simulator.😂

**Comment by swiftyfinch** [comment]
> This wouldn't help. My project need both arm and x86 arch to run on simulator.😂

This solution should work on each platform)
On inter it will be x86_64 sim, on m1 it will be amr64.
But if you need to build x86_64 on m1, you can use `rugby -a x86_64` instead of auto.

**Comment by swiftyfinch** [comment]
@mlch911 Hello! I've just released [the final 2.0.0 version](https://github.com/swiftyfinch/Rugby/releases/tag/2.0.0).
You can try to use it for auto-detecting an architecture.
I solved some problems and checked it on build agent pool with different architectures.

I'm closing this request, because the main branch changed dramatically.

**Pull request closed without merging**
